#Don't put comments below this line or they will get moved by the 'aa' function which sorts this file.
alias b='bundle'
alias bcm='./build_clinic_manager_engine_acceptance.sh && ./build_clinic_manager_engine_non_acceptance.sh'
alias blg='bundle list | grep'
alias c='rails console --irb=pry'
alias cm='cd engines/clinic_manager'
alias crd='cap review deploy'
alias crdm='cap review deploy:migrations'
alias gpr='gplr'
alias pp='engines/patient_portal'
alias ppath='echo $PATH'
alias rbdb='rake db:rebuild && rake db:test:prepare'
alias rc='rails c'
alias t='tree .'
alias tma='tmux attach'
alias wtf='wwta $1'
alias wwta='alias | grep $1'
alias zea='vim ~/code/personal_settings/yadr/custom/zsh/after/after.zsh'
alias zeaf='vim ~/code/personal_settings/yadr_custom/zsh/after/function.zsh'
alias zeal='vim ~/code/personal_settings/yadr/custom/zsh/after/alias.zsh'
alias zeb='vim ~/code/personal_settings/yadr/custom/zsh/before/before.zsh'
