#Comments can be added inline after the alias definition.
#Don't put comments below this line or they will get moved by the 'aa' function which sorts this file.
alias '#'='goxmp'
alias -0='cd -0' #aliases that make the expansion of '-' work
alias -10='cd -10'
alias -1='cd -1'
alias -2='cd -2'
alias -3='cd -3'
alias -4='cd -4'
alias -5='cd -5'
alias -6='cd -6'
alias -7='cd -7'
alias -8='cd -8'
alias -9='cd -9'
alias -g GIST='| gist -eo'
alias add_lines='sed "/$1/{x;p;x;}"' #add blank lines above lines matching a pattern
alias b='bundle'
alias big_files='du -a /var | sort -n -r | head -n 10' #
alias blg='bundle list | grep $1' #grep the list of bundled gems
alias bx='bundle exec' #execute the command prefixed with bundle exec
alias commify='sed "s/$/,/g"' #
alias crdm='cap review deploy:migrations' #depoy to review with migrations
alias cwd='pwd | pbcopy' #copy the current working directory
alias deploy='crdm' #
alias fix_dns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;' #
alias gauth='git commit --amend --reset-author' #fixup the author on the last commit
alias gcra='git commit --amend --reset-author' #fixup the author on the last commit
alias gls='git log -S$1' #search the git log for where a change was introduced or something was removed
alias goog='open https://www.google.com/search\?q\="$(pbpaste | xargs)"' #
alias gopair='chmod 777 /tmp/pair' #open a pairing socket
alias gpr='gplr' #git pull --rebase
alias grbc='git rebase --continue' #
alias iex='rlwrap -m ''\'' -a dummy iex' #
alias lnd='ls -ld *(/om[1])' # list the newest directory
alias lnf='ls *(.om[1])' # list the newest file
alias ppath='echo $PATH' #echo the PATH
alias rc='rails c' #rails console
alias rdbr='rake db:rebuild && rake db:test:prepare' #rake db:rebuild and prepare test
alias rmrf='rm -rf' #
alias rsd='rspec --format documentation' #run rspec and print test names
alias scon='v ~/.ssh/config' #open ssh config in vim
alias t='tree .'
alias tips='vim ~/code/personal_settings/tips/tips.md' #
alias tma='tmux attach' #attach to open tmux session
alias tools='v ~/code/personal_settings/tips/tool_sharpening.md' #
alias tpair='tmux -S /tmp/pair' #create a tmux socket for pairing... chmod 777 /tmp/pair when you get in there.
alias upstream='git pull upstream master' #
alias v.='vim .'
alias v='vim'
alias wwta='alias | grep $1' #what was that alias
alias zaplines='sed "/^$/d"' #remove all blank lines from a input
alias zea='emacs ~/code/personal_settings/yadr_custom/zsh/after/after.zsh' #edit zsh settings
alias zeaf='emacs ~/code/personal_settings/yadr_custom/zsh/after/function.zsh' #edit zsh funtions
alias zeal='emacs ~/code/personal_settings/yadr_custom/zsh/after/alias.zsh' #edit zsh aliases
alias zeb='emacs ~/code/personal_settings/yadr_custom/zsh/before/before.zsh' #edit zsh settings
